Repository Automattic/Cron-Control, pull requests merged in 2021-11, with the labels that each got.

#213 Add new --queue-size & --queue-window args to the orchestrator's "list-due-batch" CLI
  includes/class-events.php
  includes/wp-cli/class-orchestrate-runner.php
  tests/tests/class-events.php
Labels: needs review

#212 Fix incorrect invocation of `is_callable()`
  includes/wp-cli.php
Labels: bug

#143 Allow REST endpoints to be blocked should runner be used exclusively
  README.md
  includes/class-rest-api.php
Labels: needs review

#175 Pass status code to wp_send_json_error()
  includes/class-main.php
Labels: needs review

#214 Add GitHub workflows
  .github/checkstyle-problem-matcher.json
  .github/dependabot.yml
  .github/workflows/ci-grunt.yaml
  .github/workflows/ci-php.yaml
  .github/workflows/phpcs.yaml
  .gitignore
  .travis.yml
  Gruntfile.js
  README.md
  bin/test.sh
  composer.json
  composer.lock
  includes/class-events-store.php
  includes/class-rest-api.php
  includes/wp-cli/class-events.php
  includes/wp-cli/class-orchestrate-sites.php
  languages/cron-control.pot
  package-lock.json
  package.json
  phpcs.xml
  phpunit.xml
  readme.txt
  tests/bootstrap.php
  tests/tests/class-events-store-tests.php
  tests/tests/class-events.php
  tests/tests/class-internal-events-tests.php
  tests/tests/class-misc-tests.php
  tests/tests/class-rest-api-tests.php
  tests/tests/class-utils-tests.php
Labels: enhancement, needs review
